version: '3.6'

services:
  db:
    container_name: mysqldb
    image: mysql:5.7
    ports:
      - "32001:3306"
    environment:
      #MYSQL_DATABASE: wikipediaDB
      #MYSQL_USER: freenow
      #MYSQL_PASSWORD: freenow
      MYSQL_ROOT_PASSWORD: root

  app:
    container_name: myapp
    links: 
      - "db"
    build: ./
    ports:
      - "5001:5000"